-- MySQL Script generated by MySQL Workbench
-- Wed Apr 15 00:42:28 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `db` ;

-- -----------------------------------------------------
-- Table `db`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password_hash` VARCHAR(256) NOT NULL,
  `email` VARCHAR(256) NOT NULL,
  `estado` ENUM('activo', 'inactivo', 'bloqueado', 'suspendido') NOT NULL DEFAULT 'activo',
  `requiere_cambio_pass` TINYINT(1) NOT NULL DEFAULT 1,
  `intentos_fallidos` INT NOT NULL DEFAULT 0,
  `bloqueado_hasta` DATETIME NULL DEFAULT NULL,
  `ultimo_login` DATETIME NULL DEFAULT NULL,
  `fecha_alta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idioma_iso` VARCHAR(5) NOT NULL DEFAULT 'es',
  `twofa_habilitado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `uq_username` (`username` ASC) VISIBLE,
  UNIQUE INDEX `uq_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Cuentas de acceso al sistema';


-- -----------------------------------------------------
-- Table `db`.`password_historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`password_historial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `password_hash` VARCHAR(256) NOT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_ph_usuario` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_ph_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE)
ENGINE = InnoDB
COMMENT = 'Historial funcional de passwords para validar no-reutilización';


-- -----------------------------------------------------
-- Table `db`.`preguntas_seguridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`preguntas_seguridad` (
  `id_pregunta` INT NOT NULL AUTO_INCREMENT,
  `pregunta` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_pregunta`))
ENGINE = InnoDB
COMMENT = 'Catálogo de preguntas de seguridad';


-- -----------------------------------------------------
-- Table `db`.`respuestas_seguridad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`respuestas_seguridad` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_pregunta` INT NOT NULL,
  `respuesta_hash` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_usuario_pregunta` (`id_usuario` ASC, `id_pregunta` ASC) VISIBLE,
  INDEX `fk_rs_pregunta` (`id_pregunta` ASC) VISIBLE,
  CONSTRAINT `fk_rs_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_rs_pregunta`
    FOREIGN KEY (`id_pregunta`)
    REFERENCES `db`.`preguntas_seguridad` (`id_pregunta`))
ENGINE = InnoDB
COMMENT = 'Respuestas de seguridad por usuario';


-- -----------------------------------------------------
-- Table `db`.`permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`permisos` (
  `id_permiso` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(100) NOT NULL COMMENT 'ej: usuarios.alta, ventas.ver',
  `descripcion` VARCHAR(256) NOT NULL,
  `modulo` VARCHAR(100) NOT NULL COMMENT 'Agrupación: usuarios, ventas, stock...',
  PRIMARY KEY (`id_permiso`),
  UNIQUE INDEX `uq_permiso_codigo` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Permisos atómicos del sistema agrupados por módulo';


-- -----------------------------------------------------
-- Table `db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`roles` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(128) NOT NULL,
  `descripcion` VARCHAR(256) NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_rol`),
  UNIQUE INDEX `uq_rol_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Roles del sistema (agrupaciones de permisos)';


-- -----------------------------------------------------
-- Table `db`.`rol_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`rol_permisos` (
  `id_rol` INT NOT NULL,
  `id_permiso` INT NOT NULL,
  PRIMARY KEY (`id_rol`, `id_permiso`),
  INDEX `fk_rp_permiso` (`id_permiso` ASC) VISIBLE,
  CONSTRAINT `fk_rp_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `db`.`roles` (`id_rol`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_rp_permiso`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `db`.`permisos` (`id_permiso`)
    ON DELETE CASCADE)
ENGINE = InnoDB
COMMENT = 'Pivot: qué permisos tiene cada rol';


-- -----------------------------------------------------
-- Table `db`.`usuario_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`usuario_roles` (
  `id_usuario` INT NOT NULL,
  `id_rol` INT NOT NULL,
  `fecha_asignacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_expiracion` DATETIME NULL,
  PRIMARY KEY (`id_usuario`, `id_rol`),
  INDEX `fk_ur_rol` (`id_rol` ASC) VISIBLE,
  CONSTRAINT `fk_ur_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_ur_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `db`.`roles` (`id_rol`)
    ON DELETE CASCADE)
ENGINE = InnoDB
COMMENT = 'Roles asignados a cada usuario';


-- -----------------------------------------------------
-- Table `db`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`paises` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo` CHAR(2) NOT NULL COMMENT 'ISO 3166-1 alpha-2, ej: AR, US',
  PRIMARY KEY (`id_pais`),
  UNIQUE INDEX `uq_pais_codigo` (`codigo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`provincias` (
  `id_provincia` INT NOT NULL AUTO_INCREMENT,
  `id_pais` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_provincia`),
  INDEX `fk_prov_pais` (`id_pais` ASC) VISIBLE,
  CONSTRAINT `fk_prov_pais`
    FOREIGN KEY (`id_pais`)
    REFERENCES `db`.`paises` (`id_pais`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`localidades` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `id_provincia` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `codigo_postal` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id_localidad`),
  INDEX `fk_loc_provincia` (`id_provincia` ASC) VISIBLE,
  CONSTRAINT `fk_loc_provincia`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `db`.`provincias` (`id_provincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`entidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`entidades` (
  `id_entidad` INT NOT NULL AUTO_INCREMENT,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_alta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_entidad`))
ENGINE = InnoDB
COMMENT = 'Entidad base: toda persona o empresa arranca acá';


-- -----------------------------------------------------
-- Table `db`.`fisicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`fisicas` (
  `id_entidad` INT NOT NULL COMMENT 'PK y FK a entidades (1:1)',
  `nombre` VARCHAR(128) NOT NULL,
  `apellido` VARCHAR(128) NOT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `id_usuario` INT NULL DEFAULT NULL COMMENT 'NULL si no tiene acceso al sistema',
  UNIQUE INDEX (`id_usuario` ASC) VISIBLE,
  PRIMARY KEY (`id_entidad`),
  UNIQUE INDEX `id_entidad_UNIQUE` (`id_entidad` ASC) VISIBLE,
  CONSTRAINT `fk_per_entidad`
    FOREIGN KEY (`id_entidad`)
    REFERENCES `db`.`entidades` (`id_entidad`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_per_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL)
ENGINE = InnoDB
COMMENT = 'Personas físicas. id_usuario nullable: no toda persona tiene acceso al sistema';


-- -----------------------------------------------------
-- Table `db`.`juridicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`juridicas` (
  `id_entidad` INT NOT NULL COMMENT 'PK y FK a entidades (1:1)',
  `razon_social` VARCHAR(256) NOT NULL,
  `nombre_fantasia` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id_entidad`),
  UNIQUE INDEX `id_entidad_UNIQUE` (`id_entidad` ASC) VISIBLE,
  CONSTRAINT `fk_emp_entidad`
    FOREIGN KEY (`id_entidad`)
    REFERENCES `db`.`entidades` (`id_entidad`)
    ON DELETE CASCADE)
ENGINE = InnoDB
COMMENT = 'Personas jurídicas / empresas';


-- -----------------------------------------------------
-- Table `db`.`entidad_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`entidad_tipo` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL COMMENT 'cliente, proveedor, empleado, cobrador',
  PRIMARY KEY (`id_tipo`),
  UNIQUE INDEX `uq_tipo_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Catálogo de roles de negocio de una entidad';


-- -----------------------------------------------------
-- Table `db`.`entidad_tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`entidad_tipos` (
  `id_entidad` INT NOT NULL,
  `id_tipo` INT NOT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_alta` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_entidad`, `id_tipo`),
  INDEX `fk_et_tipo` (`id_tipo` ASC) VISIBLE,
  CONSTRAINT `fk_et_entidad`
    FOREIGN KEY (`id_entidad`)
    REFERENCES `db`.`entidades` (`id_entidad`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_et_tipo`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `db`.`entidad_tipo` (`id_tipo`))
ENGINE = InnoDB
COMMENT = 'Roles de negocio asignados a cada entidad';


-- -----------------------------------------------------
-- Table `db`.`cargos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`cargos` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` VARCHAR(256) NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_cargo`),
  UNIQUE INDEX `uq_cargo_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Catálogo de cargos/puestos de trabajo';


-- -----------------------------------------------------
-- Table `db`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`empleados` (
  `id_empleado` INT NOT NULL AUTO_INCREMENT,
  `id_entidad` INT NOT NULL COMMENT 'FK a personas.id_entidad',
  `id_cargo` INT NOT NULL,
  `legajo` VARCHAR(100) NOT NULL,
  `fecha_ingreso` DATE NOT NULL,
  `fecha_egreso` DATE NULL DEFAULT NULL COMMENT 'NULL = activo',
  PRIMARY KEY (`id_empleado`),
  UNIQUE INDEX `uq_legajo` (`legajo` ASC) VISIBLE,
  INDEX `fk_emp_persona` (`id_entidad` ASC) VISIBLE,
  INDEX `fk_emp_cargo` (`id_cargo` ASC) VISIBLE,
  CONSTRAINT `fk_emp_persona`
    FOREIGN KEY (`id_entidad`)
    REFERENCES `db`.`fisicas` (`id_entidad`),
  CONSTRAINT `fk_emp_cargo`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `db`.`cargos` (`id_cargo`))
ENGINE = InnoDB
COMMENT = 'Empleados: persona + cargo + vigencia. Independiente del acceso al sistema';


-- -----------------------------------------------------
-- Table `db`.`tipo_contacto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`tipo_contacto` (
  `id_tipo_contacto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(75) NOT NULL COMMENT 'email, telefono, celular, whatsapp, instagram, linkedin...',
  PRIMARY KEY (`id_tipo_contacto`),
  UNIQUE INDEX `uq_tc_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Tipos de contacto: unifica medios de comunicación y redes sociales';


-- -----------------------------------------------------
-- Table `db`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`contactos` (
  `id_contacto` INT NOT NULL AUTO_INCREMENT,
  `id_entidad` INT NOT NULL,
  `id_tipo_contacto` INT NOT NULL,
  `valor` VARCHAR(256) NOT NULL,
  `etiqueta` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Administración, Ventas, Personal...',
  `es_principal` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_contacto`),
  INDEX `idx_con_entidad` (`id_entidad` ASC) VISIBLE,
  INDEX `fk_con_tipo` (`id_tipo_contacto` ASC) VISIBLE,
  CONSTRAINT `fk_con_entidad`
    FOREIGN KEY (`id_entidad`)
    REFERENCES `db`.`entidades` (`id_entidad`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_con_tipo`
    FOREIGN KEY (`id_tipo_contacto`)
    REFERENCES `db`.`tipo_contacto` (`id_tipo_contacto`))
ENGINE = InnoDB
COMMENT = 'Todos los medios de contacto de una entidad';


-- -----------------------------------------------------
-- Table `db`.`tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`tipo_documento` (
  `id_tipo_documento` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL COMMENT 'DNI, CUIT, CUIL, Pasaporte',
  `aplica_a` ENUM('persona', 'empresa', 'ambos') NOT NULL DEFAULT 'ambos',
  PRIMARY KEY (`id_tipo_documento`),
  UNIQUE INDEX `uq_td_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`documentos` (
  `id_documento` INT NOT NULL AUTO_INCREMENT,
  `id_entidad` INT NOT NULL,
  `id_tipo_documento` INT NOT NULL,
  `valor` VARCHAR(128) NOT NULL,
  `es_principal` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_documento`),
  INDEX `idx_doc_entidad` (`id_entidad` ASC) VISIBLE,
  INDEX `fk_doc_tipo` (`id_tipo_documento` ASC) VISIBLE,
  CONSTRAINT `fk_doc_entidad`
    FOREIGN KEY (`id_entidad`)
    REFERENCES `db`.`entidades` (`id_entidad`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_doc_tipo`
    FOREIGN KEY (`id_tipo_documento`)
    REFERENCES `db`.`tipo_documento` (`id_tipo_documento`))
ENGINE = InnoDB
COMMENT = 'Documentos de identificación de entidades';


-- -----------------------------------------------------
-- Table `db`.`domicilios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`domicilios` (
  `id_domicilio` INT NOT NULL AUTO_INCREMENT,
  `id_entidad` INT NOT NULL,
  `id_localidad` INT NOT NULL,
  `calle` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(20) NULL DEFAULT NULL,
  `piso` VARCHAR(20) NULL DEFAULT NULL,
  `depto` VARCHAR(20) NULL DEFAULT NULL,
  `referencia` VARCHAR(512) NULL DEFAULT NULL,
  `tipo` VARCHAR(50) NULL DEFAULT NULL COMMENT 'fiscal, comercial, entrega, deposito...',
  `es_principal` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_domicilio`),
  INDEX `idx_dom_entidad` (`id_entidad` ASC) VISIBLE,
  INDEX `fk_dom_localidad` (`id_localidad` ASC) VISIBLE,
  CONSTRAINT `fk_dom_entidad`
    FOREIGN KEY (`id_entidad`)
    REFERENCES `db`.`entidades` (`id_entidad`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_dom_localidad`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `db`.`localidades` (`id_localidad`))
ENGINE = InnoDB
COMMENT = 'Domicilios de entidades. Múltiples por entidad con tipo y principal';


-- -----------------------------------------------------
-- Table `db`.`tipo_accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`tipo_accion` (
  `id_accion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_accion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db`.`auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`auditoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `id_accion` INT NOT NULL COMMENT 'LOGIN, LOGOUT, INSERT, UPDATE, DELETE, CAMBIO_ESTADO, CAMBIO_ROL, CAMBIO_PASS, BLOQUEO, etc.',
  `tabla` VARCHAR(128) NULL DEFAULT NULL COMMENT 'Tabla afectada (NULL para eventos de sesión)',
  `id_registro` INT NULL DEFAULT NULL COMMENT 'ID del registro afectado',
  `valor_anterior` TEXT NULL DEFAULT NULL,
  `valor_nuevo` TEXT NULL DEFAULT NULL,
  `id_usuario_responsable` INT NULL DEFAULT NULL COMMENT 'Sin FK: el registro debe sobrevivir aunque el usuario se elimine',
  `motivo` VARCHAR(512) NULL DEFAULT NULL,
  `fecha` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_aud_accion` (`id_accion` ASC) VISIBLE,
  INDEX `idx_aud_tabla` (`tabla` ASC, `id_registro` ASC) VISIBLE,
  INDEX `idx_aud_usuario` (`id_usuario_responsable` ASC) VISIBLE,
  INDEX `idx_aud_fecha` (`fecha` ASC) VISIBLE,
  CONSTRAINT `id_accion`
    FOREIGN KEY (`id_accion`)
    REFERENCES `db`.`tipo_accion` (`id_accion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Registro inmutable de todos los eventos críticos del sistema. Sin FKs por diseño.';


-- -----------------------------------------------------
-- Table `db`.`configuracion_sistema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`configuracion_sistema` (
  `id_config` INT NOT NULL DEFAULT 1,
  `pass_min_chars` INT NULL DEFAULT 12,
  `pass_max_chars` INT NULL DEFAULT 128,
  `pass_requiere_mayusculas` TINYINT(1) NOT NULL DEFAULT 1,
  `pass_min_minusculas` INT NULL DEFAULT 2,
  `pass_requiere_minusculas` TINYINT(1) NOT NULL DEFAULT 1,
  `pass_min_mayusculas` INT NULL DEFAULT 2,
  `pass_requiere_numeros` TINYINT(1) NOT NULL DEFAULT 1,
  `pass_min_numeros` INT NULL DEFAULT 2,
  `pass_requiere_simbolos` TINYINT(1) NOT NULL DEFAULT 0,
  `pass_simbolos_permitidos` VARCHAR(100) NULL DEFAULT '._-@#&*',
  `pass_min_simbolos` INT NULL DEFAULT 2,
  `pass_no_repetir_nunca` TINYINT(1) NOT NULL DEFAULT 1,
  `pass_no_repetir_ultimas` INT NULL DEFAULT 5,
  `pass_no_datos_personales` TINYINT(1) NOT NULL DEFAULT 1,
  `pass_no_repetir_consecutivos` TINYINT(1) NOT NULL DEFAULT 1,
  `pass_vigencia_dias` INT NOT NULL DEFAULT 90,
  `login_intentos_max` INT NOT NULL DEFAULT 6,
  `login_bloqueo_minutos` INT NOT NULL DEFAULT 15,
  `preguntas_cantidad` INT NOT NULL DEFAULT 3,
  `twofa_digitos` INT NOT NULL DEFAULT 6,
  `twofa_expiracion_min` INT NOT NULL DEFAULT 10,
  `id_usuario_modifico` INT NULL DEFAULT NULL,
  `fecha_modificacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_config`),
  INDEX `fk_cs_usuario` (`id_usuario_modifico` ASC) VISIBLE,
  CONSTRAINT `fk_cs_usuario`
    FOREIGN KEY (`id_usuario_modifico`)
    REFERENCES `db`.`usuarios` (`id_usuario`)
    ON DELETE SET NULL)
ENGINE = InnoDB
COMMENT = 'Configuración global del sistema. Siempre una sola fila (id=1)';


-- -----------------------------------------------------
-- Table `db`.`usuario_permisos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`usuario_permisos` (
  `id_usuario` INT NOT NULL,
  `id_permiso` INT NOT NULL,
  `fecha_asignacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_expiracion` DATETIME NULL,
  PRIMARY KEY (`id_usuario`, `id_permiso`),
  INDEX `id_permiso_idx` (`id_permiso` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE,
  CONSTRAINT `id_permiso`
    FOREIGN KEY (`id_permiso`)
    REFERENCES `db`.`permisos` (`id_permiso`)
    ON DELETE CASCADE)
ENGINE = InnoDB
COMMENT = 'Roles asignados a cada usuario';


-- -----------------------------------------------------
-- Table `db`.`familias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`familias` (
  `id_familia` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(128) NOT NULL,
  `descripcion` VARCHAR(256) NULL DEFAULT NULL,
  `activo` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_familia`),
  UNIQUE INDEX `uq_rol_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = 'Roles del sistema (agrupaciones de permisos)';


-- -----------------------------------------------------
-- Table `db`.`usuario_familias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`usuario_familias` (
  `id_usuario` INT NOT NULL,
  `id_familia` INT NOT NULL,
  `fecha_asignacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_expiracion` DATETIME NULL,
  PRIMARY KEY (`id_usuario`, `id_familia`),
  INDEX `id_familia_idx` (`id_familia` ASC) VISIBLE,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `db`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE,
  CONSTRAINT `id_familia`
    FOREIGN KEY (`id_familia`)
    REFERENCES `db`.`familias` (`id_familia`)
    ON DELETE CASCADE)
ENGINE = InnoDB
COMMENT = 'Roles asignados a cada usuario';


-- -----------------------------------------------------
-- Table `db`.`familia_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`familia_roles` (
  `id_familia` INT NOT NULL,
  `id_rol` INT NOT NULL,
  PRIMARY KEY (`id_familia`, `id_rol`),
  CONSTRAINT `id_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `db`.`roles` (`id_rol`)
    ON DELETE CASCADE,
  CONSTRAINT `id_familia`
    FOREIGN KEY (`id_familia`)
    REFERENCES `db`.`familias` (`id_familia`)
    ON DELETE CASCADE)
ENGINE = InnoDB
COMMENT = 'Pivot: qué permisos tiene cada rol';


-- -----------------------------------------------------
-- Table `db`.`fisicas_juridicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db`.`fisicas_juridicas` (
  `id_fisicas` INT NOT NULL,
  `id_juridica` INT NOT NULL,
  PRIMARY KEY (`id_fisicas`, `id_juridica`),
  INDEX `id_juridicas_idx` (`id_juridica` ASC) VISIBLE,
  CONSTRAINT `id_fisica`
    FOREIGN KEY (`id_fisicas`)
    REFERENCES `db`.`fisicas` (`id_entidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_juridicas`
    FOREIGN KEY (`id_juridica`)
    REFERENCES `db`.`juridicas` (`id_entidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
